# Generated by Django 4.0.1 on 2023-06-25 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issued_ticket',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('update_on', models.DateTimeField(auto_now=True)),
                ('number_of_travelers', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('pax_name', models.CharField(max_length=30)),
                ('care_of', models.CharField(blank=True, max_length=30, null=True)),
                ('booked_on', models.DateField()),
                ('depature_date', models.DateField(blank=True, null=True)),
                ('pnr', models.CharField(blank=True, max_length=7, null=True)),
                ('depature_time', models.TimeField(blank=True, null=True)),
                ('payed', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=30)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('appoinment_date', models.DateField(blank=True, null=True)),
                ('care_of', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('appoinment_time', models.TimeField(blank=True, null=True)),
                ('pass_seva_username', models.CharField(blank=True, max_length=20, null=True)),
                ('pass_seva_password', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('payed', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('appoinment_type', models.CharField(blank=True, max_length=18, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applied_visa',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=20)),
                ('pass_issue', models.DateField(blank=True, null=True)),
                ('pass_expiry', models.DateField(blank=True, null=True)),
                ('care_of', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('remitted_date', models.DateField(blank=True, null=True)),
                ('pass_number', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('visa_type', models.CharField(max_length=15)),
                ('visa_mode', models.CharField(max_length=15)),
                ('payed', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
