# Generated by Django 4.0.1 on 2023-06-25 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_issued_ticket_appoinment_applied_visa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(blank=True, max_length=24, null=True)),
                ('short_name', models.CharField(blank=True, max_length=8, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('country', models.CharField(max_length=20)),
                ('airport_name', models.CharField(max_length=20)),
                ('airport_code', models.CharField(max_length=4)),
                ('airport_place', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='applied_visa',
            old_name='payed',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='appoinment',
            old_name='payed',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='issued_ticket',
            old_name='payed',
            new_name='paid',
        ),
        migrations.CreateModel(
            name='Attastation',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pass_number', models.CharField(blank=True, max_length=10, null=True)),
                ('applicant_name', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('care_of', models.CharField(blank=True, max_length=30, null=True)),
                ('remitted_date', models.DateField(blank=True, null=True)),
                ('paid', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('agancy_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('debit_or_credit', models.BooleanField()),
                ('net_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=8, null=True)),
                ('transaction_method', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='applied_visa',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
        ),
        migrations.AddField(
            model_name='appoinment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttransation'),
        ),
        migrations.AddField(
            model_name='issued_ticket',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agency'),
        ),
    ]
