# Generated by Django 4.0.1 on 2023-06-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_country_abstractedpassport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ailine_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='country',
            old_name='ailine_name',
            new_name='contry_name',
        ),
        migrations.AddField(
            model_name='applied_visa',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='applied_visa',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttransation'),
        ),
        migrations.AddField(
            model_name='attastation',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttransation'),
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issued_ticket',
            name='arrival_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='api.airport'),
        ),
        migrations.AddField(
            model_name='issued_ticket',
            name='depature_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.airport'),
        ),
        migrations.AddField(
            model_name='issued_ticket',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accounttransation'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TicketOnSale',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seats', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('contact', models.CharField(blank=True, max_length=13, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.airline')),
                ('arrival_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
                ('depature_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depature', to='api.airport')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='issued_ticket',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.airline'),
        ),
    ]
