# Generated by Django 4.0.1 on 2023-06-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_airline_rename_ailine_name_country_contry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='staff_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
