# Generated by Django 4.0.1 on 2023-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_newuser_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('applicant_name', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=13, null=True)),
                ('seats', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('pass_number', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.airport')),
                ('depature_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depaturePort', to='api.airport')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
