# Generated by Django 4.0.1 on 2023-07-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticketrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='airport_place',
            new_name='airport_plac',
        ),
    ]
