# Generated by Django 4.0.1 on 2023-07-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_airport_place_airport_airport_plac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='airport_plac',
            new_name='airport_place',
        ),
    ]
