# Generated by Django 4.0.1 on 2023-07-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_airport_plac_airport_airport_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_place',
            field=models.CharField(max_length=50),
        ),
    ]
