# Generated by Django 4.0.1 on 2023-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_airport_airport_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
