# Generated by Django 4.0.1 on 2023-07-15 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_airport_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
