# Generated by Django 4.0.1 on 2023-07-16 10:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_airline_ailine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_visa',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
