# Generated by Django 4.0.1 on 2023-07-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_applied_visa_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='ailine_name',
            new_name='airline_name',
        ),
    ]
