# Generated by Django 4.0.1 on 2023-07-19 03:07

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_ailine_name_airline_airline_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attastation',
            old_name='agancy_name',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='ticketonsale',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='ticketrequest',
            old_name='contact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='attastation',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attastation',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
