# Generated by Django 4.0.1 on 2023-07-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_agancy_name_attastation_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_ticket',
            name='number_of_travelers',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
