# Generated by Django 4.0.1 on 2023-07-19 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_issued_ticket_number_of_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued_ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
