# Generated by Django 4.0.1 on 2023-07-19 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_issued_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_visa',
            name='applicant_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applied_visa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
