# Generated by Django 4.0.1 on 2023-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_ticketonsale_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='attastation',
            name='certificate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
