# Generated by Django 4.0.1 on 2023-07-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_newuser_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransation',
            old_name='date',
            new_name='transaction_date',
        ),
    ]
