# Generated by Django 4.0.1 on 2023-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_date_accounttransation_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransation',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
