# Generated by Django 4.0.1 on 2023-08-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_accounttransation_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketonsale',
            old_name='time',
            new_name='arrival_time',
        ),
        migrations.AddField(
            model_name='ticketonsale',
            name='depature_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
