# Generated by Django 4.0.1 on 2023-08-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_time_ticketonsale_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='seats',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
