# Generated by Django 4.0.1 on 2023-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_newuser_address_newuser_district_newuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
